### ISSUE TITLE
Panic on jpeg decoding - 'arithmetic operation overflowed'

### ISSUE THREAD

**Issue by petevine** [PistonDevelopers/image#512]
```rust

$ RUST_BACKTRACE=1  target/debug/termpix ~/20150927_132716_4.jpg

thread '<main>' panicked at 'arithmetic operation overflowed', /tmp/.cargo/registry/src/github.com-48ad6e4054423464/image-0.6.1/./src/jpeg/entropy.rs:72
stack backtrace:
   1: 0xb6ece003 - sys::backtrace::tracing::imp::write::h311da18a237e11cbCwu
   2: 0xb6ed05b7 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43435
   3: 0xb6ed013b - panicking::default_handler::h5f11ee536b41224dh5y
   4: 0xb6ec48e7 - sys_common::unwind::begin_unwind_inner::h82ccd237a30e90f9rlt
   5: 0xb6ec4dfb - sys_common::unwind::begin_unwind_fmt::hea5e4184b1dce43axkt
   6: 0xb6ecd6d3 - rust_begin_unwind
   7: 0xb6edab4f - panicking::panic_fmt::h3bb7fa6aea08ffce6YL
   8: 0xb6edae83 - panicking::panic::h784e4f1e6ec3b162DXL
   9: 0xb6d3ef43 - jpeg::entropy::HuffDecoder::consume::h604a899f98b9c1764Gh
                at /tmp/.cargo/registry/src/github.com-48ad6e4054423464/image-0.6.1/./src/jpeg/entropy.rs:72
  10: 0xb6cbd453 - jpeg::entropy::HuffDecoder::read_bit::h9690522580836537806
                at /tmp/.cargo/registry/src/github.com-48ad6e4054423464/image-0.6.1/./src/jpeg/entropy.rs:55
  11: 0xb6cbc9c7 - jpeg::entropy::HuffDecoder::decode_symbol::h11180015013453476069
                at /tmp/.cargo/registry/src/github.com-48ad6e4054423464/image-0.6.1/./src/jpeg/entropy.rs:88
  12: 0xb6cbbd3b - jpeg::decoder::JPEGDecoder<R>::decode_block::h7542827939323231879
                at /tmp/.cargo/registry/src/github.com-48ad6e4054423464/image-0.6.1/./src/jpeg/decoder.rs:219
  13: 0xb6cba857 - jpeg::decoder::JPEGDecoder<R>::decode_mcu::h1218775753725330016
                at /tmp/.cargo/registry/src/github.com-48ad6e4054423464/image-0.6.1/./src/jpeg/decoder.rs:199
  14: 0xb6cb9fdb - jpeg::decoder::JPEGDecoder<R>::decode_mcu_row::h16162608817487521931
                at /tmp/.cargo/registry/src/github.com-48ad6e4054423464/image-0.6.1/./src/jpeg/decoder.rs:175
  15: 0xb6cb998f - jpeg::decoder::JPEGDecoder<R>.ImageDecoder::read_scanline::h13815096480666228047
                at /tmp/.cargo/registry/src/github.com-48ad6e4054423464/image-0.6.1/./src/jpeg/decoder.rs:583
  16: 0xb6cb92c7 - jpeg::decoder::JPEGDecoder<R>.ImageDecoder::read_image::h4892350624154059759
                at /tmp/.cargo/registry/src/github.com-48ad6e4054423464/image-0.6.1/./src/jpeg/decoder.rs:607
  17: 0xb6ca7bab - dynimage::decoder_to_image::h2838274139883101419
                at /tmp/.cargo/registry/src/github.com-48ad6e4054423464/image-0.6.1/./src/dynimage.rs:444
  18: 0xb6c8f8a7 - dynimage::load::h3180508617358449101
                at /tmp/.cargo/registry/src/github.com-48ad6e4054423464/image-0.6.1/./src/dynimage.rs:585
  19: 0xb6c8cc1f - dynimage::open::h2937060482025689750
                at /tmp/.cargo/registry/src/github.com-48ad6e4054423464/image-0.6.1/./src/dynimage.rs:545
  20: 0xb6c83d4b - main::hcce947281a3d55c23da
                at src/main.rs:51
````

I was using yesterday's rustc nightly `1.8`, NEON is normally enabled by default. 

Before that crash, a few other jpegs were successfully decoded.

I managed to get another type of crash caused by lack of SOF2 support but there's an issue about it already.

**Comment by sp3d** [comment]
I'm seeing the same backtrace (modulo hashes) on x86_64.

**Comment by petevine** [comment]
Oh, great - then it's a cross-platform bug not related to arm, neon or even 32bits :)

**Comment by petevine** [comment]
Among maybe 2 dozen images I've tried through a script, just these two fail to load:

[exif_dump.txt](https://github.com/PistonDevelopers/image/files/137169/exif_dump.txt)
[exif_dump2.txt](https://github.com/PistonDevelopers/image/files/137171/exif_dump2.txt)

Another file from the same camera loads fine:
[exif_dump3.txt](https://github.com/PistonDevelopers/image/files/137177/exif_dump3.txt)
