### ISSUE TITLE
PPMDecoder takes a large amount of memory/time to fail decoding this non-PPM image

### ISSUE THREAD

**Issue by nagisa** [PistonDevelopers/image#627]
This small file causes PPM decoder to allocate what seems to be about 2.5GB of resident memory:

```
R0lGOGFHSUY4YUdJRjhhIDkyMjIyMjIyIDkNIDkgOQ0AAABHSUY4YQ0AAAAgOQ0AAOMAAP//
```

### Test code:

```
extern crate image;

use image::ImageDecoder;

fn main() {
    let f = ::std::fs::File::open("oom.ppm").unwrap();
    let x = image::ppm::PPMDecoder::new(f).unwrap().read_image().unwrap();
}
```

#### Tested in two ways:

```
$ time ./target/release/examples/overallocbmp
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }) })', /checkout/src/libcore/result.rs:860
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Command exited with non-zero status 101
99% (0.84 real, 0.74 kernel, 0.09 user); 2437564k resident
0 major/608015 minor pfaults; 0 swaps; 445 invol/1 vol contexts
0 inputs/0 outputs; 0 sck sent/0 sck recv; 0 signals recv
```

and 

```
$ ulimit -Sv 2000000 # 2 gigabytes of virtual memory (not resident, can't figure how to actually apply other ulimits)
$ time ./target/release/examples/overallocbmp
fatal runtime error: out of memory
Command terminated by signal 4
5% (0.05 real, 0.00 kernel, 0.00 user); 6276k resident
0 major/105 minor pfaults; 0 swaps; 4 invol/2 vol contexts
0 inputs/0 outputs; 0 sck sent/0 sck recv; 0 signals recv
```

### How I found it:

fuzzing against gif corpus resulted in OOM at a particular time when my system was low-ish on memory.

### Other notes:

If compiled without optimisations, decoder takes a very long time (10s of seconds) to fail. You can then observe the memory use slowly rising up.

This image has invalid header format for a PPM image. Namely, nowhere in the file there is a `P6` magic number these images ought to have, so it seems to me like decoding should fail very quickly.

**Comment by HeroicKatora** [comment]
Fixed in the rewrite of `pnm`. Sorry for the late response.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FormatError("Expected magic constant for pnm, P1 through P7 instead of [82, 48]")', libcore/result.rs:1009:5
```
